// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrlwxqjvisjulcnilcyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlybHd4cWp2aXNqdWxjbmlsY3liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4MzM1ODYsImV4cCI6MjA4OTQwOTU4Nn0.mBxs_v-9aVrURbJ-PbSsP15r-jD-kc9xfgEx4pk77b8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});